### ISSUE TITLE
Font rendering on wasm/web?

### ISSUE THREAD

**Issue by ChristopherBiscardi** [StarArawn/kayak_ui#108]
Heya!

Is kayak's font rendering supposed to work on wasm? Everything else seems to work (ninepatch, on_event, styles, etc), but the fonts aren't rendering at all in the wasm port of my game. I also don't see any errors in the console and such.

The buttons here should have some text on them.

<img width="391" alt="image" src="https://user-images.githubusercontent.com/551247/165593914-889305a3-e679-45ab-81b8-00d6c5aec446.png">

**Comment by StarArawn** [comment]
Yes! This is a known issue. It's due to a bug in wGPU which prevents us from creating a texture array in webGL 2. Even though it is possible.

**Comment by MrGVSV** [comment]
Hm. Did you set your font default in the `FontMapping` resource?

**Comment by ChristopherBiscardi** [comment]
Is that this issue? https://github.com/gfx-rs/wgpu/issues/2161

**Comment by StarArawn** [comment]
> Is that this issue? [gfx-rs/wgpu#2161](https://github.com/gfx-rs/wgpu/issues/2161)

No, I worked around that by avoiding numbers divisible by 6. I was working on tracking it down so I could provide an actual error to the WGPU team, but I got sidetracked. The issue occurs because of the `copy_texture_to_texture` wgpu command I'm using to copy data from an atlas to an array texture.

**Comment by MrGVSV** [comment]
> No, I worked around that by avoiding numbers divisible by 6.

😳

**Comment by StarArawn** [comment]
This might be more fixable as of bevy 0.8.

**Comment by StarArawn** [comment]
This is now fixed when using TTF fonts directly! Take a look at the clipping example or the book to learn more. 👍
