### ISSUE TITLE
nine_patch flips the border vertically

### ISSUE THREAD

**Issue by ChristopherBiscardi** [StarArawn/kayak_ui#111]
If you replace the nine_patch image example with this image.

![metalPanel_blueCorner](https://user-images.githubusercontent.com/551247/169424165-ce684603-eb1f-4632-92a9-7504a566cfd5.png)

you can see that the border is flipped in the y direction (and that the border seems to be stretched.

<img width="1382" alt="image" src="https://user-images.githubusercontent.com/551247/169424132-72410e48-375f-41f1-9101-f990ebd09105.png">

This *also* happens with the default nine_patch image example, but it is harder to see. 

![panel](https://user-images.githubusercontent.com/551247/169424410-2f42e7cc-9d29-44d9-9f19-39b7e6589414.png)

If you focus on the bordering red/black lines you can see the top-left corner in the origin image is the bottom-left corner in the rendering.

<img width="1382" alt="image" src="https://user-images.githubusercontent.com/551247/169424394-ba635c3a-7834-4ef8-9715-bfd4ef7014af.png">

---

Additionally, the measurements seem to be off. In both cases the Edge::all needs to be doubled to fit the right size of pixels (from 30 to 60 for the new image, and from 15 to 30 for the old), and even then the borders appear stretched.

ex: new image at `Edge::all(30.0)` (which should be the right pixel count for the border).

<img width="1382" alt="image" src="https://user-images.githubusercontent.com/551247/169425389-c8ba9242-0613-4fff-b3da-cc1ca4309df3.png">

and `Edge::all(60.0)`

<img width="1382" alt="image" src="https://user-images.githubusercontent.com/551247/169425328-c921a6df-50b9-401f-9e4e-90664eb4b757.png">

The panel I was expecting looks more like this (it's a kenney asset from the space ui set)

![Sample](https://user-images.githubusercontent.com/551247/169425579-940d32f3-d48e-4873-bb45-56107f6de4a6.png)

**Comment by StarArawn** [comment]
Fixed with the rewrite! 👍 Please reopen if you feel as though this is still an issue.
