### ISSUE TITLE
examples don't work 

### ISSUE THREAD

**Issue by AnotherCoolDude** [StarArawn/kayak_ui#113]
I am trying to run the examples (unmodified), but every example results in the attached screenshot. 
There is no error message unfortunately, the app seems to run despite not showing anything. 
I am running windows 10. So far, I tried the examples "counter", "todo" and "text_box".
Any clue on how to make it work?

![image](https://user-images.githubusercontent.com/11141338/170693881-cbe235e5-a0af-4072-8ae4-8b5511827870.png)

**Comment by StarArawn** [comment]
Do the bevy examples work? What I'm seeing in your screenshot is very strange.

**Comment by AnotherCoolDude** [comment]
just tried "bevy_state" and it looks different, but still isn't working. 
Tried the same examples on my macbook, same results. Am I doing something fundamentally wrong (cargo run --example bevy_state)? It works well for you?

![image](https://user-images.githubusercontent.com/11141338/170700437-c7184bbe-c018-43be-a494-14691f3b2145.png)

**Comment by StarArawn** [comment]
I did find an issue. Can you pull again and see if it works now? Thanks!

**Comment by AnotherCoolDude** [comment]
works now, thank you very much!
