### ISSUE TITLE
Support for bevy 0.7

### ISSUE THREAD

**Issue by mwbryant** [StarArawn/kayak_ui#116]
Is there a specific problem with using this with bevy 0.7? I've successfully been using it with 0.7 in 2 projects but I want to make sure there's not a pitfall awaiting me

**Comment by SteveXCIV** [comment]
Also wondering the same thing. PR #102 says it start[ed] the 0.7 upgrade, but reading the discussion, it's not exactly clear what's not finished. Does the README just need to be updated to say "Use bevy 0.7"?

**Comment by MrGVSV** [comment]
Yep! It should be working fine on 0.7. 😄 

> Does the README just need to be updated to say "Use bevy 0.7"?

Looks like it. That should definitely say 0.7. Feel free to open a PR fixing that if you want haha

**Comment by StarArawn** [comment]
O.7 should be supported. Feel free to open a PR to update the readme. Otherwise I'll get to it eventually. 👍
