### ISSUE TITLE
Shader structs aren't 16-byte aligned

### ISSUE THREAD

**Issue by Commander-lol** [StarArawn/kayak_ui#142]
When running the latest version of `kayak_ui` on the web, the app will throw an error at startup complaining that the flag `BUFFER_BINDINGS_NOT_16_BYTE_ALIGNED` is not supported. Tracking down the [docs for wgpu](https://wgpu.rs/doc/wgpu/struct.DownlevelFlags.html#associatedconstant.BUFFER_BINDINGS_NOT_16_BYTE_ALIGNED), this flag is simply not supported by webgl

Basically, the structs used in `unified_pipeline` shader (`shader.wgsl`) aren't laid out in a multiple of 16 bytes. One possible solution would be to pad the structs with unused data to make sure they're a multiple of 16 - I was trying to get this working, but ended up hitting a knowledge gap

More information about alignment & sizes [in this Learn Wgpu article](https://sotrh.github.io/learn-wgpu/showcase/alignment/#alignment-of-uniform-and-storage-buffers) and [in the W3 spec for WGSL](https://www.w3.org/TR/WGSL/#memory-layouts)

It seems a bit odd that this wouldn't have come up before, but I'm also quite unfamiliar with wgsl and shaders in general - there may be something else that is causing this

The specific error message I get (Chrom on Ubuntu 22.04): 

![Screenshot from 2022-08-19 00-24-07](https://user-images.githubusercontent.com/2522620/185512066-131220f0-7d95-46ac-afd7-368e1f2d2fa0.png)

**Comment by StarArawn** [comment]
Yeah we should be able to do this by changing the values in the shader.
