### ISSUE TITLE
Fatal error when rendering to target with different size than window

### ISSUE THREAD

**Issue by tqwewe** [StarArawn/kayak_ui#144]
I have an app which uses postprocess, so renders to an image texture. Though, the image texture is not 1:1 with the window size, and instead is scaled down (for a post processing effect).

Spawning a `UICameraBundle` with the target set to this image texture causes a fatal panic to occur when the game opens.
```
2022-08-27T13:33:19.585318Z ERROR wgpu::backend::direct: Handling wgpu errors as fatal by default    
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In a RenderPass
      note: encoder = `<CommandBuffer-(0, 106, Vulkan)>`
    In a set_scissor_rect command
    Scissor Rect { x: 0, y: 0, w: 1280, h: 720 } is not contained in the render target Extent3d { width: 640, height: 360, depth_or_array_layers: 1 }

', /home/ari/.cargo/git/checkouts/wgpu-a5140d1891ddccc5/a703a78/wgpu/src/backend/direct.rs:2391:5
note: run with `RUST_BACKTRACE=1` environment variable to display a **backtrace**
```

This issue does not occur with the built-in bevy cameras, but does occur with Kayak UI.

**Comment by StarArawn** [comment]
@tqwewe This is because the default way we grab width/height in the app is like:
https://github.com/StarArawn/kayak_ui/blob/main/src/widgets/app.rs#L52

This obviously doesn't work when the target is a render target. I think instead we should query the camera and pull the width and height from the window if the window is the target otherwise pull it from the render target image.

**Comment by tqwewe** [comment]
Thanks for the quick reply!
Yeah from the camera makes sense, I think that should solve it

**Comment by StarArawn** [comment]
In the meantime you can use a custom built app that takes width and height.

**Comment by StarArawn** [comment]
Fixed with the rewrite! 👍 Please reopen if you feel as though this is still an issue.
