### ISSUE TITLE
Panic when resizing application window

### ISSUE THREAD

**Issue by ickk** [StarArawn/kayak_ui#15]
On commit: 81fc2a4ee84ea7f827c9ed7fac57afc50849ab1d

When resizing any window the application panics with the following message:

```
wgpu::backend::direct: Handling wgpu errors as fatal by default
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In a RenderPass
      note: encoder = `<CommandBuffer-(0, 11974, Vulkan)>`
    In a set_scissor_rect command
    Invalid ScissorRect parameters
```

**Comment by StarArawn** [comment]
I think this is because in the examples we set the app styles to the window size, but we never update them when they change. I'll look into it more, it likely will involve adding a BevyApp widget that tracks the window changes.
