### ISSUE TITLE
UICameraBundle Issues

### ISSUE THREAD

**Issue by lecoqjacob** [StarArawn/kayak_ui#165]
Piggybacking on my previous issue, I have a state flow setup to go from asset_load -> menu -> ingame. Each with a different UI layout.

If I do not inject a `UICameraBundle` at startup, but instead inject this when building says the main_menu UI, it offsets it towards the top left of the screen. 

<img width="1140" alt="CleanShot 2022-11-14 at 12 50 18@2x" src="https://user-images.githubusercontent.com/9278174/201741697-da1c2ad7-eb7c-4984-87f9-3dd36493f560.png">

If instead, I inject a `UICameraBundle` at startup, then manipulate the RootContext via the enter system of main_menu
```rust
pub fn setup_main_menu(
    mut commands: Commands,
    textures: Res<TextureAssets>,
    asset_server: Res<AssetServer>,
    mut font_mapping: ResMut<FontMapping>,
    mut ctx: Query<(Entity, &mut KayakRootContext)>,
) {
    if let Ok((root_entity, mut widget_context)) = ctx.get_single_mut() {
        font_mapping.set_default(asset_server.load("fonts/lato/lato-light.kayak_font"));

        widget_context.add_plugin(KayakWidgetsContextPlugin);
        ...
```

Then the menu is correctly centered within the screen.

<img width="1045" alt="CleanShot 2022-11-14 at 12 52 03@2x" src="https://user-images.githubusercontent.com/9278174/201741965-41530582-83af-4db4-83c8-cd544e0e5e6b.png">

**Comment by lecoqjacob** [comment]
Got a minimal setup going to reproduce the bug. I just output the styles attached to the app.
```rust
for styles in q.iter() {
     println!("App: {:?}", styles);
}
```

The first json  is the style on KayakApp using startup_system, and the following is using states and only injecting the camera after 1 state has passed.
```json
{
  background_color: Unset,
  border_color: Unset,
  border_radius: Unset,
  border: Unset,
  bottom: Unset,
  color: Unset,
  col_between: Unset,
  cursor: Unset,
  font: Unset,
  font_size: Unset,
  height: Value(Pixels(720.0)),
  layout_type: Unset,
  left: Unset,
  line_height: Unset,
  max_height: Unset,
  max_width: Unset,
  min_height: Unset,
  min_width: Unset,
  offset: Unset,
  padding: Unset,
  padding_bottom: Unset,
  padding_left: Unset,
  padding_right: Unset,
  padding_top: Unset,
  pointer_events: Unset,
  position_type: Unset,
  render_command: Value(Layout),
  right: Unset,
  row_between: Unset,
  top: Unset,
  width: Value(Pixels(1280.0)),
  z_index: Unset,
}

```


```json
{
  background_color: Unset,
  border_color: Unset,
  border_radius: Unset,
  border: Unset,
  bottom: Unset,
  color: Unset,
  col_between: Unset,
  cursor: Unset,
  font: Unset,
  font_size: Unset,
  height: Value(Pixels(720.0)),
  layout_type: Unset,
  left: Unset,
  line_height: Unset,
  max_height: Unset,
  max_width: Unset,
  min_height: Unset,
  min_width: Unset,
  offset: Unset,
  padding: Unset,
  padding_bottom: Unset,
  padding_left: Unset,
  padding_right: Unset,
  padding_top: Unset,
  pointer_events: Unset,
  position_type: Unset,
  render_command: Value(Layout),
  right: Unset,
  row_between: Unset,
  top: Unset,
  width: Value(Pixels(1280.0)),
  z_index: Unset,
}
```

**Comment by lecoqjacob** [comment]
Did some more digging and can confirm. Inside `app_render` on initial load, if you use a startup system widthxheight = 1280x720.

On the conditional set where I use states, the following is printed to the console:
```
APP RENDER: 0 0
APP RENDER: 1280 720
```

**Comment by lecoqjacob** [comment]
oh i finally deduced the issue! The app is updating the styles, but the `text_render` update system for `TextWidgetBundle` isnt updating after the app updates its width / height

**Comment by StarArawn** [comment]
Closing this as #168 fixes the issue.
