### ISSUE TITLE
Please expose PointerEvents and KPositionType enums

### ISSUE THREAD

**Issue by kristianmandrup** [StarArawn/kayak_ui#172]
I'm working on a builder library for Kayak UI but have found that I'm unable to reference `PointerEvents` and `KPositionType` enums since they are private. Please make them public. Cheers :)

**Comment by StarArawn** [comment]
`KPositionType`  should be exposed already via the `prelude`.

**Comment by kristianmandrup** [comment]
Amazing 🤩 Thanks 👍
