### ISSUE TITLE
KPositionType::SelfDirected not working on main.

### ISSUE THREAD

**Issue by wongchongkai** [StarArawn/kayak_ui#184]
Use case: I have several menus that I would like to display and/or hide depending on the situation, which I am controlling via each widget's state:
```
<KayakAppBundle>
    <TitleMenuBundle
        styles = {
            KStyle {
                position_type: KPositionType::SelfDirected.into(),
                ..Default::default()
            }
        }
    />
    <PauseMenuMainBundle
        styles = {
            KStyle {
                position_type: KPositionType::SelfDirected.into(),
                ..Default::default()
            }
        }
    />
    <PauseMenuSaveBundle
        styles = {
            KStyle {
                position_type: KPositionType::SelfDirected.into(),
                ..Default::default()
            }
        }
    />
</KayakAppBundle>
```
![01](https://user-images.githubusercontent.com/87868708/205094188-bc7cc003-e0fb-4619-884d-44d72eb586c3.png)
![02](https://user-images.githubusercontent.com/87868708/205094238-0fca2e76-6485-4932-8b7c-9a80caa83e00.png)

The issue, of course is that they are sibling widgets, and so without setting `position_type` to `KPositionType::SelfDirected`, they end up looking like this:

![04](https://user-images.githubusercontent.com/87868708/205094608-b6cf7e86-a995-4c1f-909e-fbf5e7619908.png)

Currently, this technique works fine on the cargo version of `kayak_ui`. However, when I upgrade to `main`, this no longer works, and the menu is placed at exactly the same spot as when I did not set the `position_type` manually:

![05](https://user-images.githubusercontent.com/87868708/205098110-f0a01871-e79e-4984-bab0-e1d05f48f8a7.png)

Is this expected behavior for `main`?

**Comment by StarArawn** [comment]
Main has a big change where widgets that have styles need to "compute" the styles into a `ComputedStyles` component. You can see this here:
<https://github.com/StarArawn/kayak_ui/blob/main/src/widgets/image.rs#L41>

**Comment by wongchongkai** [comment]
Oh it works perfectly now. Thanks a lot!
