### ISSUE TITLE
KTTF Visual Weirdness

### ISSUE THREAD

**Issue by njt1968** [StarArawn/kayak_ui#195]
Trying to switch from .kayak_font to .kttf for WASM purposes, but it made some visual glitchiness:

.kayak_font: 
![image](https://user-images.githubusercontent.com/113371844/207710586-06f0c798-59a8-44d0-9fad-f3acbefae589.png)

.kttf: 
![image](https://user-images.githubusercontent.com/113371844/207710680-a335bfdc-3906-4a59-8a27-52446eeafd2f.png)

The kttf code: 
![image](https://user-images.githubusercontent.com/113371844/207710758-995cf78f-7650-4533-ad14-8f8b2af64a82.png)

Help appreciated 🤪

**Comment by StarArawn** [comment]
Hi! 

You can use the `offset_x` and `offset_y` properties. For some reason the font gets vertically offset randomly depending on the font during SDF generation. I think I'm likely not positioning it correctly on the Y axis. In any case I added the additional properties to work as a workaround.

Which version of Kayak are you using? I made some changes to adjust the sampling curve for the SDF lookup to avoid the white boxes around the characters in the latest 0.2 release, and it's a bit surprising for you to have them.

**Comment by njt1968** [comment]
Update to latest version did fix the visual noise, and after manually adjusting the Y offset, everything working fine.
Thanks for your help 😊

**Comment by njt1968** [comment]
Update:

On latest version, when using .kttf, the font looks fine on the .exe and when compiled to WASM on mobile browser, but not on Chrome/Edge on Windows.

.EXE: 
![image](https://user-images.githubusercontent.com/113371844/207929560-b35e2a7f-1fc0-4fcd-a8b8-ad1d362797bc.png)

Mobile (via WASM):
![image](https://user-images.githubusercontent.com/113371844/207929865-24a77666-dc85-46aa-8ca9-12cb3d16d380.png)

Chrome (via WASM):
![image](https://user-images.githubusercontent.com/113371844/207929352-9aca4f34-5dda-41d6-a21a-3e089c195ac4.png)

Any clue whats happening here? Wish I had more info to debug with but I am lost here

**Comment by johanhelsing** [comment]
I also get some vertical offset weirdness happening with .kttf. Happening on windows and firefox at least:

kttf:
![image](https://user-images.githubusercontent.com/2620557/208244917-4450165f-3fba-467d-8aad-b89796f118da.png)

kayak_font:
![image](https://user-images.githubusercontent.com/2620557/208244948-6ae45d55-d734-4357-b6d8-fbe3c691e328.png)

**Comment by StarArawn** [comment]
> I also get some vertical offset weirdness happening with .kttf. Happening on windows and firefox at least:
> 
> kttf:
> ![image](https://user-images.githubusercontent.com/2620557/208244917-4450165f-3fba-467d-8aad-b89796f118da.png)
> 
> kayak_font:
> ![image](https://user-images.githubusercontent.com/2620557/208244948-6ae45d55-d734-4357-b6d8-fbe3c691e328.png)
> 

This happens because the positioning in the font sdf generation is wrong. It seems to be different per font. I did add an offset_x and offset_y as a work around until I can fix it.

**Comment by StarArawn** [comment]
> Any clue whats happening here? Wish I had more info to debug with but I am lost here

I'm not sure I'll try to take a look soon.

**Comment by AnActualEmerald** [comment]
I'm getting the same visual noise on kttf fonts, and it seems to be related to the font size somehow. 

The default roboto font from this repo with `size` set to 20.0 in the `TextProps`
![20.0px size](https://user-images.githubusercontent.com/4367791/210156627-c7b586bb-64de-42d8-aaa2-34b7033afb6f.png)

The same font with `size` set to 15.0
![15.0px size](https://user-images.githubusercontent.com/4367791/210156671-5aa78ab2-f7ee-4004-9c90-489bf92a283b.png)

This happens for me in both wasm on firefox and native on Fedora Linux under Wayland

**Comment by johanhelsing** [comment]
I also have the white stripes issue only on some font sizes:

![kayak_ui_text_issues](https://user-images.githubusercontent.com/2620557/210966098-cfa560b1-cd55-42ce-8c3f-b9cc215838f3.png)
 
It's consistent across firefox, chrome and native windows. It only seems to happen on non-hidpi screens.

**Comment by StarArawn** [comment]
Can you see if this PR fixes things?
https://github.com/StarArawn/kayak_ui/pull/221
