### ISSUE TITLE
None of the examples work for me

### ISSUE THREAD

**Issue by 1moeses** [StarArawn/kayak_ui#215]
When I let them run, eg. :

```
cargo run --example tabs
```

I always get:
```
WARN kayak_ui::input: Couldn't find primiary window! 
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/widgets/app.rs:63:64
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
see also:
https://github.com/StarArawn/kayak_ui/issues/202#issuecomment-1384426538

**Comment by yzn-h** [comment]
same issue for me running pop os

**Comment by Zrocket** [comment]
I'm also having this problem on Manjaro.

**Comment by StarArawn** [comment]
I'm unsure how to fix this issue as I don't have linux setup. Do the bevy examples work for you?

**Comment by yzn-h** [comment]
after cloning the repo and running the example it works for some reason

**Comment by StarArawn** [comment]
I'm going to close this issue. Please reopen if you still think this is an issue. :)
