### ISSUE TITLE
New widgets replacing old ones in the tree aren't recognized as changed

### ISSUE THREAD

**Issue by NiseVoid** [StarArawn/kayak_ui#216]
When rendering a widget with different but similarly structured contents, the new widgets don't always get rendered.

I made an isolated example of this issue. Clicking the red square (or the green/blue square inside it) should change it to the other color. However the new color doesn't show up. Changing `widget_update` to `update_widget_with_tab` on line 47 and 54 makes it work, but this feels more like a hack than an actual solution. If either of the widgets has a different style from the other it'll also update fine, so it seems to be comparing these two different widgets in `widget_param.has_changed`.

The example:
[kayak_example.zip](https://github.com/StarArawn/kayak_ui/files/10745440/kayak_example.zip)

**Comment by StarArawn** [comment]
Can you try this with the latest code from here:
https://github.com/StarArawn/kayak_ui/pull/220

**Comment by NiseVoid** [comment]
Tested it with the new code, still happens. Here is the updated example:
[kayak_example.zip](https://github.com/StarArawn/kayak_ui/files/11094711/kayak_example.zip)

**Comment by StarArawn** [comment]
This PR should address a fix for the issue!
https://github.com/StarArawn/kayak_ui/pull/221

**Comment by StarArawn** [comment]
Closing this as it is fixed.
