### ISSUE TITLE
Tabs example crashes

### ISSUE THREAD

**Issue by YoshieraHuang** [StarArawn/kayak_ui#250]
When I run the tabs example, if I switch to tab 2 and then switch back to tab 1, the example crashes and says "unwrap on a Option::None value".

**Comment by StarArawn** [comment]
Have you tested with the latest main? Quite a few bugs have been fixed. What is the stack trace?

**Comment by StarArawn** [comment]
I tested this on main and it works fine on my machine.

**Comment by YoshieraHuang** [comment]
I tried latest and it works.
