### ISSUE TITLE
hello_world example is blank when copied into project

### ISSUE THREAD

**Issue by keywordsalad** [StarArawn/kayak_ui#265]
I've copied the hello_world example code into my project as the only content of the main.rs file. When I run it, I get a gray window with no content. However, when I run the example directly from the kayak_ui source repo, I see "hello world" in the window as expected.

I'm using bevy 0.10.1, but the problem also exists with 0.10.0.

**Comment by StarArawn** [comment]
Did you copy the font file?

**Comment by keywordsalad** [comment]
That's what was missing. Thanks!

Would it make sense to emit a log error or panic if the font doesn't exist?

**Comment by StarArawn** [comment]
You should get a bevy asset warning. It's easy to miss though.
