### ISSUE TITLE
Add `rustfmt.toml`

### ISSUE THREAD

**Issue by MrGVSV** [StarArawn/kayak_ui#41]
To better maintain style consistency within the codebase, a `rustfmt.toml` file should be added to allow automatic formatting of code.

**Comment by StarArawn** [comment]
Code auto formats for me on save, but yes rustfmt.toml would help! 👍

**Comment by IceSentry** [comment]
A rustfmt.toml isn't required if we use the default rustfmt configs, but it could be added as a CI step to enforce it on PRs

**Comment by StarArawn** [comment]
CI is checking formatting now. Do we still need a rustfmt.toml? I think we can just keep using the default config.

**Comment by IceSentry** [comment]
I don't think a rustfmt.toml is necessary if you are fine with the default config.

**Comment by MrGVSV** [comment]
I think default should be fine for now.
