### ISSUE TITLE
UI getting clipped

### ISSUE THREAD

**Issue by MrGVSV** [StarArawn/kayak_ui#42]
## Problem

For some reason the UI is getting clipped at 50% width and 50% height of the window:

<img width="1382" alt="clipped" src="https://user-images.githubusercontent.com/49806985/147172769-56b4111c-30a0-4fd9-a980-fdaad62f6d11.png">

I'm not sure if this is another DPI issue or an OS issue.

## Details

**Machine:** MacBook Pro (15-inch, 2019)
**OS:** macOS 11.6 Big Sur
**Display:** 15.4-inch (2880 × 1800)

**Comment by StarArawn** [comment]
Looks like a DPI issue again. I made some changes here so I'll check..

**Comment by MrGVSV** [comment]
Fixed by ab1c63e1d6887338d29990c0feef0ffdb1c6fb08
