### ISSUE TITLE
asset_server loads font as .png to fontMapping when in another Bevy app

### ISSUE THREAD

**Issue by RobertoSnap** [StarArawn/kayak_ui#47]
## Expected
Run Bevy example(https://github.com/StarArawn/kayak_ui/blob/main/examples/bevy.rs) in own repo.

## Tried: 
- Cloned and ran the example from kayak_ui repo (branch https://github.com/StarArawn/kayak_ui/tree/update-bevy) with success.
- Cleared lock file and cargo clean.

## Error
![CleanShot 2022-01-03 at 10 34 34](https://user-images.githubusercontent.com/4772930/147916335-175fa827-1609-416c-94f2-136e81d3e7ae.png)
```bash
2022-01-03T09:34:19.890068Z  WARN bevy_asset::asset_server: encountered an error while reading an asset: path not found: /Users/robin/code/bevy/galactic/client/assets/roboto.png
thread 'main' panicked at 'attempt to subtract with overflow', /Users/robin/.cargo/git/checkouts/kayak_ui-299a0b6ac8320811/e25baa9/bevy_kayak_ui/src/render/unified/pipeline.rs:595:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## Re-produce steps:
- Clone https://github.com/RobertoSnap/galactic/tree/1d98e9c7ccd6d704fdd45873042e4ee8b2e863a4
- Run cargo run (defaults to client where the error happens)

## Version

```toml
kayak_ui = { git="https://github.com/StarArawn/kayak_ui", rev="e25baa9d0ae0cbb63c07e1f3153af2da5c69b8f4" } (branch update-bevy)
bevy = {git = "https://github.com/bevyengine/bevy.git", commit = "1d0d8a3397bd6fc2c14d42ffd0668d2443748912"}
```

**Comment by RobertoSnap** [comment]
Tried running it again, then it dident panic and  ran

![CleanShot 2022-01-03 at 10 51 47](https://user-images.githubusercontent.com/4772930/147917646-f758e80e-085c-4976-8588-fc9f2291d4ce.png)

But with warning

![CleanShot 2022-01-03 at 10 50 08](https://user-images.githubusercontent.com/4772930/147917576-fd2c5292-2ead-4449-b0b8-f260c6881eea.png)

**Comment by StarArawn** [comment]
It's not finding the font texture atlas files. If you are trying to load `roboto.kayak_font` in you need to have the associated png file as well. 

Here is where you load in that font file:
https://github.com/RobertoSnap/galactic/blob/1d98e9c7ccd6d704fdd45873042e4ee8b2e863a4/client/src/main.rs#L46
 
I don't see a `roboto.png` file located here:
https://github.com/RobertoSnap/galactic/tree/1d98e9c7ccd6d704fdd45873042e4ee8b2e863a4/client/assets

**Comment by RobertoSnap** [comment]
> It's not finding the font texture atlas files. If you are trying to load `roboto.kayak_font` in you need to have the associated png file as well. 
> 
> 
> 
> Here is where you load in that font file:
> 
> https://github.com/RobertoSnap/galactic/blob/1d98e9c7ccd6d704fdd45873042e4ee8b2e863a4/client/src/main.rs#L46
> 
>  
> 
> I don't see a `roboto.png` file located here:
> 
> https://github.com/RobertoSnap/galactic/tree/1d98e9c7ccd6d704fdd45873042e4ee8b2e863a4/client/assets

Ahh, offcourse. I need the font file🙈

Thank you!
