### ISSUE TITLE
Link to kayak widgets in readme.md broken

### ISSUE THREAD

**Issue by HoboDev** [StarArawn/kayak_ui#78]
This link: https://github.com/StarArawn/kayak_ui/blob/main/kayak_widgets
under topic "Features" in bullet point:

- A few default widgets check out [kayak_widgets](https://github.com/StarArawn/kayak_ui/blob/main/kayak_widgets)!

shows a 404 not found page.

**Comment by StarArawn** [comment]
Thanks! We'll make sure to get this updated in the meantime you can find the widgets here:
https://github.com/StarArawn/kayak_ui/tree/main/src/widgets
