### ISSUE TITLE
Add opacity

### ISSUE THREAD

**Issue by MrGVSV** [StarArawn/kayak_ui#88]
## Problem

Currently, there's no way to set the opacity of a widget. This is important when creating overlays and other UI effects.

## Solution

Add an `opacity` style property. This property should match the effect of CSS's [`opacity`](https://developer.mozilla.org/en-US/docs/Web/CSS/opacity). It should:

* Range from 0.0 (inclusive) to 1.0 (inclusive)
* Default to an initial value of 1.0
* Apply to not only itself, but _all_ descendants
  * Values stack: a descendant's opacity is compounded by all ancestors' opacities
    * This includes inherited opacities

### Additional Considerations

The [W3 specs](https://www.w3.org/TR/css-color-3/#transparency) state that opacities less than 1.0 create a new stacking context. This is because you can't position elements between a non-opaque element and its children (see [this example](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context#the_example)).

I'm not sure how we resolve z-indexes and such so this may or may not be something we need to consider as well. We also may not even need to enforce this if we can properly handle the scenario stated above.

**Comment by StarArawn** [comment]
Added in: #232
