### ISSUE TITLE
Not rendering anything

### ISSUE THREAD

**Issue by ghmendonca** [StarArawn/kayak_ui#94]
I am trying to render an ui when I get in a specific state, but for some reason nothing is getting rendered in the window.

This is my App configurations
![image](https://user-images.githubusercontent.com/29390554/160981417-db8b32d3-f63c-449b-a720-1bb0cb3e4dec.png)

And this is my system which should render some texts
![image](https://user-images.githubusercontent.com/29390554/160981490-2cae782c-92a9-4be4-8cec-ee2df880a409.png)

I am using this commit version `135e513e8d7f197d04dacfb1c5e8c48db3cb5621`

I'm on windows 11, nvidia graphic card and intel processor

**Comment by MrGVSV** [comment]
Does the `Window` render? The text won't render since it looks like you didn't add a font asset (unless that was setup in another system).

**Comment by ghmendonca** [comment]
The window opens as usual. I'm not loading any font asset, didn't know this was required. Let me try that

**Comment by MrGVSV** [comment]
> I'm not loading any font asset, didn't know this was required. 

Yeah it's required to render text (I believe you need both the PNG and the kayak_font, but I could be wrong).

Hopefully, we can get the book finished soon so stuff like this is a little more discoverable :)

**Comment by ghmendonca** [comment]
@MrGVSV just loaded the font and still not rendering anything. Have both png and kayak_font. No errors on console.

![image](https://user-images.githubusercontent.com/29390554/160990686-f1f0ec66-6bf9-438a-94a8-0ab17f43aed0.png)

**Comment by MrGVSV** [comment]
Oh it also looks like you’re missing the `UICameraBundle`. Yo I'll need to spawn that in as well.

**Comment by ghmendonca** [comment]
@MrGVSV it works! I was using the wrong `UICameraBundle`, I was importing from bevy and not kayak. Thanks!
