### ISSUE TITLE
Image widget width gets wider the further it's x-axis is away from the window border

### ISSUE THREAD

**Issue by ChristopherBiscardi** [StarArawn/kayak_ui#97]
The [image example](https://github.com/StarArawn/kayak_ui/blob/6e83e926706e4541c4e4535cbb4e8de7bc3e9a47/examples/image.rs) appears fine on first run

```
cargo run --example image
```

<img width="1382" alt="image" src="https://user-images.githubusercontent.com/551247/162638667-80c9c8e3-66b2-4865-9267-fd2b49d982bd.png">

but the further the image is from the left or the top, the more stretched it becomes. Almost as if the width of the image is tied to the x coordinate, and the height tied to the y coordinate.

```
left: StyleProp::Value(Units::Pixels(500.0)),
```

<img width="1588" alt="image" src="https://user-images.githubusercontent.com/551247/162638618-1ef4b453-d842-4f3f-9147-fb674f381818.png">

**Comment by StarArawn** [comment]
@ChristopherBiscardi 
This should be fixed now. Let me know if you have any other issues!

**Comment by ChristopherBiscardi** [comment]
Awesome! it works for me now, thanks!
